DROP TABLE  IF EXISTS USER;
CREATE TABLE USER(
	id INT(11) AUTO_INCREMENT,
	username VARCHAR(50) DEFAULT NULL,
	PASSWORD VARCHAR(20) DEFAULT NULL,
	PRIMARY KEY(id)
)ENGINE=INNODB AUTO_INCREMENT=2 CHARSET=utf8;